#+title: Aware of the Stars
#+author: joshministers.com
#+email: josh.ministers@gmail.com
#+date: 2023-1-27
#+tags: ['devotional']
#+layout: PostSimple
#+options: prop:t todo:nil num:nil toc:nil

* Aware of the Stars
** Preparation                                                     :noexport:
goal: Motivate people to push themselves

What if there's something beautiful you can do in the world, but the reason you
choose not to is because you're not willing to push yourself?


Having different experiences help grows your awareness, helps you realize what
you are actually capable of doing..

My friend Jocelyn recommended me a book, I ordered it not knowing it was over
700 pages long. I didn't think I could read a book that long, usually my
attention drifts very easily. It wasn't until I was challenged with that new
experience I became aware that yes, it is capable.

The amazing things you can do don't just have to be academic, or for your
career. You may be the perfect person to help a friend through a difficult
time. The perfect person to show a smile... etc.

"Push yourself, you may find stars you didn't know were there."

We really don't know what we are capable of doing.

In two sense really.

1. We don't know how capable we are of accomplishing affecting the world around us
2. We don't know how capable we are to experience peace.

The second may be surprising, so i think I'm going to hold off on talking about
it until after I go through everything.   

On point 2
[[bible:Phillippians 4:6-7]]

#+begin_quote
6 Be anxious for nothing, but in everything by prayer and supplication, with
thanksgiving, let your requests be made known to God; 7 and the peace of God,
which surpasses all understanding, will guard your hearts and minds through
Christ Jesus.
#+end_quote

This expresses the ideal state to be in. As we see because it mentions that the
things that make use anxious we should recognize and then leave them up to
God. What that also means is that the peace spoken about in the second verse,
verse 7, is attainable!

Now that may require changing your life. You may not feel at peace until you
give something up that you know God wants you to give up. You may not feel at
peace until you work towards balancing your life better. You may not feel peace
until you decide to forgive htat person who did that one thing.

Peace is attainable where you are.

The problem is that we often want to attain peace on our own merits. We want to
have peace and live our lives the way we selfishly want to.

We don't want to follow God's way at peace, but follow our own selfish ways.

- Rather than forgiving a person that wronged us, we harbor hatred.
- Rather than assuming the best about others we gossip
- Rather than looking to serve others, we try to fulfill out own interests.

This book right here (the bible) has been around for over two thousand
years. Whether you believe in the spiritual claims of Christianity or not, you
have to admit that it's brought people peace for over two thousand years.

Why not instead of trying forge people our own way, we look to see how God and
the bible tells us we can receive peace.

And it starts simply, [[bible:Matthew 11:28-30]]

#+begin_quote
28 Come to Me, all you who labor and are heavy laden, and I will give you
rest. 29 Take My yoke upon you and learn from Me, for I am gentle and lowly in
heart, and you will find rest for your souls. 30 For My yoke is easy and My
burden is light.”
#+end_quote

It starts with taking Christ on and learning from Him. Choosing to stop doing it
our way. We'll be shoked to realize peace is not that far away.

*** DONE Create mini album with coolest star photos for vespers
DEADLINE: <2023-01-27 Fri 06:30>
*** Sequence
- Did you see what was outside? It was absolutely breath taking
- We don't realize how much we truly are capable of doing

** Introduction

A PDF version of this article is available [[asset:/assets/aware-of-the-stars.pdf][here]]

Did anyone see what was outside? What's outside is absolutely breath taking. Can
Anyone guess what it is?

I'll give it in the form of a riddle. It's larger than the largest sea, but
still can hid behind a tree.

I went to Arizona over winter break, and it was an amazing experiences. On my
first night, I remember looking up and being absolutely amazed by the
stars. I felt like I hadn't ever seen stars so clearly before. These are just a
few of the many pictures I took.

I told my friend about a week into my trip about how beautiful the stars seem to
shine in Arizona. And he, also being from North Carolina, told me, "Dude, the
stars are just as bright in North Carolina as here."

I thought he was just being a fanboy of Carolina, but when I got back, I looked
up, and low and behold, the stars were gorgeous. I couldn't believe it, I've
lived here for two and a half years and yet haven't once noticed how beautiful
the stars were.

Now, me going to Arizona obviously wasn't what caused North Carolina to get more
beautiful stars. The stars were always there, what needed to change was
my... *awareness*

Better put:

#+begin_quote
The stars were */always there/*

I just needed to be */made aware/*
#+end_quote

** There can be beauty

When I realized how unaware I was of the beauty that laid above me I immediately
started thinking of a billion analogies you can make to life with it. The most
obvious one was "don't be so tunnel visioned that you neglect to see the beauty
around you". Another valid one was even when you're going through the muck there
are beautiful stars around you.

But the analogy I liked the most to this experience is how unaware we are of the
beauty we can have in our lives.

** Don't accept an ugly life

I remember I was in a meeting for a ministry, and one of the members ended with
a prayer in which he prayed that God would allow us to execute our plan
stress-free. When he finished the prayer I chimed in quick saying, "Yeaa
hopefully we do well, but I highly doubt what you say about us doing it all
stress free is even possible."

To me, it was inconceivable that I could live a life where everything I did did
not put stress on my heart. After living with that reality for so long it just
became a matter of fact, any burden you take on necessarily has to add a
component of stress that makes your life a little bit more miserable.

Then everyone in the meeting was like, "WHAT Josh." In essence, they told me: "Have
you looked up to notice the stars?" That it is possible.

And that was the reality I was living in. Even when they tried convincing me
that it was possible for me to live a life where I didn't have to constantly
feel burdened I couldn't imagine it.

Why do we just accept lives without peace?

Just because you look up and are in a situation devoid of peace, doesn't mean
it has to stay like that.

[[bible:Phillippians 4:6-7]]
#+begin_quote
6 Be anxious for nothing, but in everything by prayer and supplication, with
thanksgiving, let your requests be made known to God; 7 and the peace of God,
which surpasses all understanding, will guard your hearts and minds through
Christ Jesus.
#+end_quote

This expresses the ideal state to be in. It mentions that there are things that
typically make us anxious and that we should recognize them. He goes forward
from that and says for us to leave them up to God. What that means is that the
peace spoken about in the second verse, verse 7, is attainable through some kind
of process!

Peace is attainable where you are.

The problem is that we often want to attain peace on our own merits. We want to
have peace and live our lives the way we selfishly want to.

We don't want to follow God's way at peace, but follow our own selfish ways.

- Rather than forgiving a person that wronged us, we harbor hatred.
- Rather than assuming the best about others we gossip
- Rather than looking to serve others, we try to fulfill out own interests.

This book right here (the bible) has been around for over two thousand
years. Whether you believe in the spiritual claims of Christianity or not, you
have to admit that it's brought people peace for over two thousand years.

Why not instead of trying forge people our own way, we look to see how God and
the bible tells us we can receive peace.

And it starts simply, [[bible:Matthew 11:28-30]]

#+begin_quote
28 Come to Me, all you who labor and are heavy laden, and I will give you
rest. 29 Take My yoke upon you and learn from Me, for I am gentle and lowly in
heart, and you will find rest for your souls. 30 For My yoke is easy and My
burden is light.”
#+end_quote

It starts with taking Christ on and learning from Him. Choosing to stop doing it
our way. We'll be shoked to realize peace is not that far away.

*** DONE Create mini album with coolest star photos for vespers
DEADLINE: <2023-01-27 Fri 06:30>
*** Sequence
- Did you see what was outside? It was absolutely breath taking
- We don't realize how much we truly are capable of doing

** Introduction

Did anyone see what was outside? What's outside is absolutely breath taking. Can
Anyone guess what they are?

They're larger than the largest sea, but still can hid behind a tree.

I went to Arizona over winter break, and it was an amazing experiences. On my
first night, I remember looking up and being absolutely amazed by the
stars. I felt like I hadn't ever seen stars so clearly before. These are just a
few of the many pictures I took.

I told my friend about a week into my trip about how beautiful the stars seem to
shine in Arizona. And he, also being from North Carolina, told me, "Dude, the
stars are just as bright in North Carolina as here."

I thought he was just being a fanboy of Carolina, but when I got back, I looked
up, and low and behold, the stars were gorgeous. I couldn't believe it, I've
lived here for two and a half years and yet haven't once noticed how beautiful
the stars were.

Now, me going to Arizona obviously wasn't what caused North Carolina to get more
beautiful stars. The stars were always there, what needed to change was
my... *awareness*

Better put:

#+begin_quote
The stars were */always there/*

I just needed to be */made aware/*
#+end_quote

** You can do more than you're aware of

When I realized how unaware I was of the beauty that laid above me I immediately
started thinking of a billion analogies you can make to life with it. The most
obvious one was "don't be so tunnel visioned that you neglect to see the beauty
around you". Another valid one was even in when you're going through the muck
there are beautiful stars you can be made aware of.

But the analogy I liked the most to this experience is...

Wait, can anyone guess what the analogy is that I liked the most. Actually I'd
love to hear the guesses, this may give me inspiration for more devotionals in
the future.

Well, the analogy I liked the most was how unaware we are of the beauty we can
attain in our lives.

** Don't accept an ugly life

I remember I was in a meeting for a ministry, and one of the members ended with
a prayer in which he prayed that God would allow us to execute our plan
stress-free. When he finished the prayer I chimed in quick saying, "Yeaa
hopefully we do well, but I highly doubt what you say about us doing it all
stress free."

To me, it was inconceivable that I could live a life where everything I did did
not put stress on my heart. After living with that reality for so long it just
became a matter of fact, any burden you take on necessarily has to add a
component of stress that makes your life a little bit more miserable.

Then everyone in the meeting was like, "WHAT Josh." In essence, they told me: "Have
you looked up to notice the stars?" That it is possible.

And that was the reality I was living in. Even when they tried convincing me
that it was possible for me to live a life where I didn't have to constantly
feel burdened I couldn't imagine it.

Why do we just accept lives without peace?

Just because you look up and are in a situation devoid of peace, doesn't mean
it has to stay like that.

#+begin_quote
6 Be anxious for nothing, but in everything by prayer and supplication, with
thanksgiving, let your requests be made known to God; 7 and the peace of God,
which surpasses all understanding, will guard your hearts and minds through
Christ Jesus.
#+end_quote

This expresses the ideal state to be in. It mentions that there are things that
make use anxious but that we should recognize them and then leave them up to
God. That also means that the peace spoken about in the second verse, verse 7,
is attainable!

Peace is attainable where you are.
** How Do You Attain this Peace?

It's a journey! It took me going to Phoenix to realize I could see beauty in the
sky. In the same way, our paths toward peace aren't straight forward.

Since that meeting I mentioned, I've made vast strides towards living a more
peacable life. I'd love to talk about that more one day.

I believe that when we start by making intentional steps towards peace we can
progressively get closer towards living a lifestyle some of us may never have
thought possible.

For me, I had to internalize a few things in order to get past the things
blocking me from experiencing peace, this included:

1. Realizing my thoughts weren't always indicative of reality
2. Making intentional steps toward prioritizing my time for things that matter
   most to me
3. Learning to trust God in my victories and failures

It was when I acknowledged the things in my life that were holding me back from
peace that I was able to start making strides towards living peacefully. And for
me that was a daily practice of repeating the things I know of in the bible as
true that countered the negative thoughts I had that drained peace from my life.

So for me, it was mostly mental

[[bible:2 Corinthians 10:5]]

#+begin_quote
5 casting down arguments and every high thing that exalts itself against the
knowledge of God, bringing every thought into captivity to the obedience of
Christ,
#+end_quote

I had to get my mental right before I was able to experience the beauty in life
that God wanted me to experience.

For some of you it may be external. You may have to learn how to forgive people,
or you may have to learn setting boundaries with others, before you can
experience the beauty in life God wants you to

But in all circumstances, I believe if we seek out God, learn about Him, try to
follow the ways laid out in the bible that we'll be on the path towards peace.

This book right here (the bible) has been giving people peace for over two
thousand years. People have been able to go through jail, torture, humiliation,
poverty, and all kind of strife. I'm sure it can help you through your life as
well.

So to summarize, and make it clear.

- We have to first recognize that we can attain peace
- Secondly recognize what's holding us back from it
- Lastly Remember it's a daily battle

** Closing

Where you are now may not be very beautiful, but you'll be surprised when you
look up after a journey with God how beautiful and peaceful it can be.
