#+title: The decision is now
#+author: joshministers.com
#+email: josh.ministers@gmail.com
#+date: 2022-11-12
#+tags: ['devotional', 'interactive']
#+layout: PostSimple
#+options: prop:t todo:nil num:nil toc:nil

* Preparation                                                     :noexport:
- Have a positive attitude when we make decisions knowing it will lead us in a
  certain direction.
- The decisions you make now will affect who you will be in the future
* Introduction
I need a volunteer, someone who is younger

Does everyone know who this is?

Now I need someone who is, let's say "less young".

You would be surprised how long I spent trying to find a way to say that that
wouldn't get me in trouble.

OK. So it's a bright, sunny, new day and both ~$YOUNGER_PERSON~ and ~$OLDER_PERSON~ wake up at the
break of dawn ready to start a new day.

It was then that it hit both of them.

They had been watching the Olympics the night before and remember seeing Simone
Biles, Gabby Douglas, and other gymnasts throw themselves in the air and do
amazing flips and twirls.

So ~$YOUNGER_PERSON~ screamed in excitement and said "I want to become a gymnast!"

and then ~$OLDER_PERSON~ screamed in excitement and said "I want to become a
gymnast!"

Both of them said they wanted to become gymnasts, and are prepared and
ready to work very very hard for it.

My question for everyone is, who has the better chance of becoming a gymnast,
~YOUNGER_PERSON~ or ~$OLDER_PERSON~

I hate to say it, but ~$YOUNGER_PERSON~ has the best chance at becoming a gymnast.

It's simply because $YOUNGER_PERSON is younger that their body will better be
able to adapt to what's required to be a gymnast.

If I, for example, were to decide to become a gymnast today,

it would be very very hard for me because the decisions I made with my body when
I was ~$YOUNGER_PERSON~'S age, has made my body work in a certain way that
would be very difficult to change at my age.

It's not technically impossible, but would certainly be very difficult.

So to summarize this, the decisions you make when you're younger can have
lasting effects on you when you are older.

You could even say, the decisions you made when you were younger and the
decisions you make NOW are shaping you into who you will be tomorrow.

* Neural Pathways

I want to read an excerpt from a science blog I found

#+begin_quote
Neural pathways are the connections that form between the neurons in your
brain. And you can think of them as a pattern that represents any thought about
anything you’ve ever had – as simple as an apple, as complicated as love and
integrity, every thought is a neural pathway.

#+end_quote
— [[https://lifexchangesolutions.com/neural-pathways/][Lifexchange]]


The basic idea with this is that every time you make a decision, you create a new
neural pathway that will make it easier for you to make that decision or think
about that thought in the future.

So when you do something repeatedly, you make that pathway easier to "walk on",
making it more likely you go back to repeating that same action.

It's the compounding of these decisions that end up forming who you are.

A quick example of this: it is found that people who donate money when they're
younger, are A LOT more likely to donate money when they're older.

It's obvious, if you are accustomed to giving money away when you get older and
have more money it'll be a lot easier to give.

That's why paying tithe on what you make is so important regardless of how much
you make or how old you are. You're putting a vote towards being someone that's
generous towards God.

That's why the bible says to parents,

[[bible:Proverbs 22:6]]
#+begin_quote
6 Train up a child in the way they should go, And when they are old they will not
depart from it.
#+end_quote

* Make your decisions wisely

Every thought you have, and every decision you make will lead you to become
more like that kind of person.

So when you react negatively and gossip against someone, you're putting a vote
towards becoming the kind of person who gossips.

When you react positively and show concern and care for someone who wronged you
or you dislike, you're putting a vote towards becoming a compassionate person.

The more you choose to follow what you know God wants you to do, the easier and
better person you will become 20 years from now.

The decisions you make now are powerful!

And for those of us who are further along in life, we can rest assured that if
God can put a camel through the eye of a needle ([[bible:Matthew 19:24-26]]), He
certainly can work to reverse the damages that our past decisions have on us.

but we should all remember, the decisions we make now, are powerful.

And to make this very practical, ask people who are older than you for advice.

They have seen the way their decisions have affected them, so they can be a
great aid in guiding your life.

Whether that's asking how to handle certain situations with friends, or just
general advice on things to look out for in life.

And it goes the other way too, older people, ask younger people for advice since
the world is much different today than it was when each one of you grew up.

[[bible:Proverbs 18:15]]
#+begin_quote
15 The heart of the prudent acquires knowledge,
And the ear of the wise seeks knowledge.
#+end_quote

So ask for advice!

And remember, the decisions you make now are powerful and will form who you will
be in the future. Make decisions that will lead you to become Godly.

* Footnotes
