#+title: What about the Sabbath?
#+author: joshministers.com
#+email: josh.ministers@gmail.com
#+date: 2022-12-03
#+tags: ['Sabbath', 'Sermon']
#+layout: PostSimple
#+options: prop:t todo:nil num:nil toc:nil


* Outline                                                          :noexport:
Speaking Time: 40 minutes

- Reaffirm that I love them ❤️‍🔥
  Say I may cut some of you with this message, but if I didn't care about you
  deeply I would never want to be the one to carry this message to try and move
  you from a path I know steeped with sin.
- What is Sabbath?
  Quick, practical. Where do we see Sabbath and why do we still follow it today.
- What do you do?
  - You spend time with your creator (Genesis 2)
    - Bible study
    - Walk with God in nature
    - Prayer/meditation 
    - You treat it as a /different/ day. (Exodus 20:8)
  - You spend time in community (Genesis 2)
    - Group fellowship
    - Group discussions on the things of God
    - Supporting one another
- How ought not be done
  - You don't work (Exodus 20:9)
  - You don't make other people work (for you, or in general) (Exodus 20:10)
  - You don't spend money (Nehemiah 10:31)
- Is it actually wrong to...?
  - Spend money on Sabbath?
    - The Sabbath is a time to say NO to consumerism.
    - The Sabbath is time to recognize that it's not the world or buying that
      gives you meaning, but God
  - To go out to eat on the Sabbath
    - When you go out to eat, get a haircut, or receive those kinds of service,
      you are treating that person less than a cow. [[bible:Exodus 20:10]], God says
      that person deserves rest and you're going against that.
  - For me to personally work on Sabbath
    - You are treating yourself less than a cow
    - You are cheating God out of time with you
    - You're spitting on Christ's sacrifice for you to be free.
- How do I practically keep Sabbath?
  - How will I eat?
    - During Covid, I bought my food before sunset and put in mini fridge
    - If you don't eat for one day, you won't die. You should much rather go hungry for
      a couple hours than desecrate God's Sabbath
  - How will I get my schoolwork done?
    - Not doing work for 1 whole day forces you to manage your time better.
    - If you make the decision not to profane the Sabbath you will find a way to
      complete all your school work
  - But I'll lose my job?
    - Much better to lose your job and get another one than to lose your life in
      the flames of hell
  - But all my Adventist friends do XYZ on Sabbath
    - [[bible:Matthew 15:14]]
    - Can't say "But my friends" on judgment day
  - Aren't there exceptions to the Sabbath rule?
    - Yes, but to the greatest extent we should try to avoid them. It shouldn't
      be our default reaction, "I'll just break Sabbath"
    - If someone is starving, delereous, and about to die and no food is on
      hand, the right thing to do would be to buy them food, or take them to
      receive service at the hospital.
    - It's when we start making exceptions the default reaction we end up profaning Sabbath.
  - You wouldn't understand
    - BUT JOSH, you don't have this much school work, or have to make this much
      sacrifice, or blah blah
    - Talk about basketball testimony.
    - EMPHASIZE CHRIST'S SACRIFICE

I don't think I'm going to say this last part, I'm going to focus on the emotion
after I finish telling the basketball story.

- Some of you still won't listen
  - After this, some of you may go home to finish studying, or go out to eat
  - You've heard this message, and you are guilty of sin now that you're in the
    know.
  - I want to end off reminding you that Christ was nailed to a cross so that
    you could spend time with you, the least you can do is close your textbook.

* Scriptures                                                       :noexport:

[[bible:Exodus 20:8-11]]
#+begin_quote
8 “Remember the Sabbath day, to keep it holy. 9 Six days you shall labor and do
all your work, 10 but the seventh day is the Sabbath of the Lord your God. In it
you shall do no work: you, nor your son, nor your daughter, nor your male
servant, nor your female servant, nor your cattle, nor your stranger who is
within your gates. 11 For in six days the Lord made the heavens and the earth,
the sea, and all that is in them, and rested the seventh day. Therefore the Lord
blessed the Sabbath day and hallowed it.
#+end_quote
[[bible:Leviticus 23:32 NIV]]
#+begin_quote
32 It is a day of sabbath rest for you, and you must deny yourselves. From the
evening of the ninth day of the month until the following evening you are to
observe your sabbath.”
#+end_quote
[[bible:Isaiah 58:13-14]]
#+begin_quote
13 “If you turn away your foot from the Sabbath, From doing your pleasure on My
holy day, And call the Sabbath a delight, The *holy day of the Lord* honorable,
And shall honor Him, not doing your own ways, Nor finding your own pleasure, Nor
speaking your own words, 14 Then *you shall delight yourself in the Lord*; And I
will cause you to ride on the high hills of the earth, And feed you with the
heritage of Jacob your father. The mouth of the Lord has spoken.”
#+end_quote
[[bible:Exodus 20:10a]]
#+begin_quote
10 but the seventh day is the Sabbath of the Lord your God. In it you shall do
no work
#+end_quote
[[bible:Exodus 20:10b]]
#+begin_quote
10 nor your son, nor your daughter, nor your male servant, nor your female
servant, *nor your cattle,* nor your stranger who is within your gates.
#+end_quote
[[bible:Nehemiah 10:31a]]
#+begin_quote
31 if the peoples of the land brought wares or any grain to sell on the Sabbath
day, we would not buy it from them on the Sabbath
#+end_quote
[[bible:Ephesians 5:15-17 ESV]]
#+begin_quote
15 Look carefully then how you walk, not as unwise but as wise, 16 making the
best use of the time, because the days are evil.
#+end_quote
[[bible:Matthew 28:20]]
#+begin_quote
lo, I am with you always, even to the end of the age.” Amen.
#+end_quote
[[bible:Matthew 15:14]]
#+begin_quote
14 Let them alone. They are blind leaders of the blind. And if the blind leads
the blind, both will fall into a ditch.”
#+end_quote
[[bible:2 Corinthians 5:10]]
#+begin_quote
10 For we must all appear before the judgment seat of Christ, that *each one* may
receive the things done in the body, according to what *he has done*, whether good
or bad.
#+end_quote
[[bible:Mark 3:4]]
#+begin_quote
4 Then He said to them, “Is it lawful on the Sabbath to do good or to do evil,
to save life or to kill?” But they kept silent.
#+end_quote

* Introduction

A PDF version of this sermon is available [[asset:/A basic look at the Sabbath.pdf][here]]

This is a sermon I created to, first, give a basic and practical overview of
what the Sabbath is and how it is kept. Secondly, explain what dishonoring
("breaking") the Sabbath looks like. And, finally, discuss why Sabbath keeping
is something we should do now as well as why it is important in our walks with
God.

The Sabbath is not just a time of rest, but a declaration of who we hold as the
provider and controller of our lives. Will you let the world and its whims
control you?

Hope You are Blessed!

* What is Sabbath

So what is the Sabbath? The Sabbath, succinctly, is a time that God set apart
every week for rest. It is not only a time set apart, but a commandment He gave
to humankind to rest. As we see in:

[[bible:Exodus 20:8-11]]
#+begin_quote
8 “Remember the Sabbath day, to keep it holy. 9 Six days you shall labor and do
all your work, 10 but the seventh day is the Sabbath of the Lord your God. In it
you shall do no work: you, nor your son, nor your daughter, nor your male
servant, nor your female servant, nor your cattle, nor your stranger who is
within your gates. 11 For in six days the Lord made the heavens and the earth,
the sea, and all that is in them, and rested the seventh day. Therefore the Lord
blessed the Sabbath day and hallowed it.
#+end_quote

We know the Jews considered a day to be the evening of one weekday to the
evening of the next weekday. So the Sabbath has been kept from sunset Friday to
sunset Saturday by people since God created the world. We see scriptural
evidence for this when God talks about a particular Sabbath being from one
evening to another ([[bible:Leviticus 23:32 NIV]]).

For a (semi) comprehensive treatment of why we should still be keeping the
Sabbath, look at my [[post:Sabbath][Sabbath article]]!

* The Spirit of the Sabbath

So then what do you spend your time doing on the Sabbath? How do you "keep
Sabbath holy" as the commandment states.

The Sabbath is a time to have your mind occupied by God. Isaiah 58 gives a good
definition of what the spirit of the Sabbath looks like:

[[bible:Isaiah 58:13-14]]
#+begin_quote
13 “If you turn away your foot from the Sabbath, From doing your pleasure on My
holy day, And call the Sabbath a delight, The *holy day of the Lord* honorable,
And shall honor Him, not doing your own ways, Nor finding your own pleasure, Nor
speaking your own words, 14 Then *you shall delight yourself in the Lord*; And I
will cause you to ride on the high hills of the earth, And feed you with the
heritage of Jacob your father. The mouth of the Lord has spoken.”
#+end_quote

So the Sabbath is a day to "delight yourself in the Lord".
/(Note: in particular this verse may be saying a result of following Sabbath is us delighting in the Lord, but the point still stands with other things
mentioned in this verse)/

You can define this, as what I already mentioned, as "having your mind occupied
by God and resting in God". Some ways of doing this include:

- Bible study
- Walking with God in nature
- Prayer/meditation
- Sabbath naps
- Watching the Chosen or any other God-centered programming

Another way to keep the Sabbath holy is to spend time in Godly community, for
example:

- Group fellowship
  - "Breaking Bread" (eating) together.
- Group discussions and studies on things related to God
- Group naps (I'm still trying to sell this idea to my friends)

The way you keep Sabbath is by making it a /different/ (that's what holy means)
day from all other days in the week. The things you do every moment ought to
bring you closer in communion with God and be restful.

If you spend every moment of every day resting, people don't call you holy, they
call you lazy!

* Things that break the spirit of the Sabbath

God is also clear on what dishonors Him on the Sabbath.

- We should not work

  
The first part of Exodus 20:10 says:

[[bible:Exodus 20:10a]]
#+begin_quote
10 but the seventh day is the Sabbath of the Lord your God. In it you shall do
no work
#+end_quote

- We should not make other people work (for us, or in general)

The second part of Exodus 20:10 says

[[bible:Exodus 20:10b]]
#+begin_quote
10 nor your son, nor your daughter, nor your male servant, nor your female
servant, *nor your cattle,* nor your stranger who is within your gates.
#+end_quote

even the COWS get to rest.

Thirdly:

- We should not spend money

[[bible:Nehemiah 10:31a]]
#+begin_quote
31 if the peoples of the land brought wares or any grain to sell on the Sabbath
day, we would not buy it from them on the Sabbath
#+end_quote

The Sabbath isn't a day to do our shopping or be a consumer.

Those are the three main things God talks about people abstaining from on the
include:
Sabbath. So to make it practical, some things that break the spirit of the Sabbath
include:
- Doing your homework (you're doing work)
- Making your kids do homework (you're making your kids work)
- Going to work (you're doing work)
- Going to a restaurant or eatery (you're making the restaurant workers work)
- Getting a haircut (you're making the hairdresser work)
- Studying on Sabbath for a test or exam (you're doing work)

Those are a few, but the general idea is already laid out in [[bible:Isaiah 58:13]]

[[bible:Isaiah 58:13]]
#+begin_quote
13 “If you turn away your foot from the Sabbath, From doing *your pleasure* on My
holy day, And call the Sabbath a delight, The holy day of the Lord honorable,
And shall honor Him, not doing *your own ways*, Nor finding your own pleasure, Nor
speaking your own words,
#+end_quote

Turn from doing what pleases you and do what pleases God. Honor Him and have
your mind set on Him. And you can't have your mind set on Him at a basketball
game, while attending a tennis tournament, or anything in between.

* Is it actually wrong to

So then the question may be raised, is it actually that wrong to do this or
that?

So let's talk about a few common examples

** Spend money on the Sabbath

The Sabbath is a time to say NO to consumerism. We have six days in the week to
buy, be capitalists and drive that pig forward, but the Sabbath is a day to say
NO, I will not derive my meaning from purchasing.

It helps you recognize that God is the provider for all things you need, not
your money or Walmart.

** Eat out on the Sabbath

When you go out to eat, get a haircut, or receive any kind of these services,
you are treating that person less than a cow.

As we read in [[bible:Exodus 20:10]], God says to give your cattle, cows, rest on
the Sabbath. You going to a restaurant or receiving work is the equivalent of
saying "This person doesn't even deserve the rest that God says a cow deserves".

And that is highly offensive to the worth that God ascribes to each person He
created.

** Me to personally work on the Sabbath

As mentioned in the previous point, you would be treating yourself less than a
cow. But if calling yourself a cow doesn't do it, you would also be doing two
things.

1. Saying you don't have time for God

Sabbath is a time for you to spend time with God.

You may be saying "I don't have time for God this week", sadly. To say that you
don't have time for God is dishonest because He is the one that provides you
with the time. It's not your time in the first place! He's the one that's given
you life, and he gives you freedom to use your time, but just asks you give back
to Him a 1/7 of it.

He specifically made the Sabbath so you don't have to worry about not having
time, he's already scheduled it for you.

If you find yourself seemingly not having enough time for God, including the
time He already set apart during the Sabbath, it's very likely you either have
to change how you manage your time or change what you spend your vocation or
time doing. God will not lead you down a path where you can't spend time with
Him.

Every situation He leads us in life will not require us to break His law.

So whenever we make that excuse, we're cheating God out of the time He wants to
spend with us.

2. Spitting on the sacrifice Christ made for you

Keeping the Sabbath is a time to recognize that God is your savior. You are not
saved by your works, but by the work God did through Christ to set you free,
that's what saves you. The moment you disobey the Sabbath, you spit on that
sacrifice Christ made to make you free. The sacrifice to give you an avenue of
freedom away from the world.

God decided to give up the comforts of heaven to come down and die on the cross
for you. The least you can do is sacrifice a bit of homework. Sacrifice a single
paycheck. Sacrifice wanting to go out to chick-fil-a.

He wants you to be free, and you choosing to enslave yourself to the world, to
your work, to your own desires, to your university, or anything else that
demands your attention is spitting on the sacrifice and pain that Christ went
through to set you free from those things.

We need to sit up one day and say NO. I'm DONE neglecting my faith anymore. I'm
DONE living for the world. I'm DONE with playing games with God.

This stuff is no joke this is life or death. Your whole being is in danger of
being lost forever because of disobedience.

And for those of you who are ready to make that step toward God, I want to give
some practical ways to keep the Sabbath.

* How do I practically keep Sabbath
** How will I eat

This one is easy, if you're in a dorm, buy all your food from your dining hall
you'll need for the next day before sunset. Thankfully many churches have
potlucks so you won't be stuck eating dining hall food for a day.

During covid, I would buy a *lot* of food a few hours before sunset Friday so
that I wouldn't have to make the dining staff work to give me food. It was a
good time for me since I stayed in my room napping to music, watching the Bible
Project videos and eating multiple (in my opinion) good meals.

If you don't have a refrigerator in your dorm building, buy nonperishable foods
to eat, or ask someone from church to have you over.

- Peanut butter, bread, jelly (you can do wonders with that)
- Minute rice with canned beans, vegetables, anything
- Be resourceful!

If all else fails, you will very likely not die from not eating for one
day. Whenever I forgot to buy my food during my freshmen year, in the days of
covid while potlucks were banned, I would "declare the day a fast to God".

** How will I get my schoolwork done

The Sabbath is a time to say that God is the most important in your
life. What you cannot deny controls you. *What you cannot deny, controls
you*. And do you want your university, your high school, to be the one
controlling you?

For those of you concerned about completing schoolwork, think about how you
spend your time in a day. Often the reason why we don't find time in the day is
that we didn't spend our time wisely.

Look at your screen time, how much of your time is spent on Youtube, Instagram,
and Tiktok? Playing any kind of video game? What if you converted that time
into time spent doing homework, you very likely will find that you complete
a lot more work in the six days than previously.

The Sabbath gives you a push on being intentional with your time. I encourage
all of you to look at how you spend your time.

[[bible:Ephesians 5:15-17 ESV]]
#+begin_quote
15 Look carefully then how you walk, not as unwise but as wise, 16 making the
best use of the time, because the days are evil.
#+end_quote

The days are not easy, it is difficult.

If you don't wake up every day and decide what you're going to be doing with
your time that day, you will find yourself wasting your time and then making
excuses on why you have to make it up on Sabbath.

You don't want to get to the end of your life and regret wasting your college
years on Youtube and Netflix, deteriorating your relationship with God because
you never kept the Sabbath since you wanted to catch up on your work.

And if you tell me that you spend all day every day working, never looking at
your phone, then it may be time to have a conversation with your professors, or
accept you may not do as well in this class as everyone else, but that it is a
worthy sacrifice to obey God's commandments and grow your relationship with Him.

Decide to not do your schoolwork on Sabbath, and then from there find a solution
to get all your schoolwork done or lower your expectations in certain classes.

** But I'll lose my job

It's much, much better to lose your job and get another one than for you to lose
your life in the lake of fire (hell).

Your job does not care about you, they will fire you in a heartbeat. They will
lay you off without a second notice. Why break Sabbath for people that don't
even care if you can pay your bills.

God, however, will *never* abandon you. Jesus says:

[[bible:Matthew 28:20]]
#+begin_quote
lo, I am with you always, even to the end of the age.” Amen.
#+end_quote

Why leave this God for a paycheck? You'll get many, many times more in heaven.

** But my family or friends do XYZ

- "My parents always made me do homework on the Sabbath"
- "An elder at my church always took us out to eat after service."
- "My friends and peers would be so much more ahead of me in class"
- "My Adventist friends always did this"

[[bible:Matthew 15:14]]
#+begin_quote
14 Let them alone. They are blind leaders of the blind. And if the blind leads
the blind, both will fall into a ditch.”
#+end_quote

Don't let those who don't obey God's word lead you to sin. You cannot, in the
final judgment, use your friends as an excuse for your own wilful sin.

[[bible:2 Corinthians 5:10]]
#+begin_quote
10 For we must all appear before the judgment seat of Christ, that *each one* may
receive the things done in the body, according to what *he has done*, whether good
or bad.
#+end_quote

We will face the judgment seat with none of our family, friends, or peers
around us. God will judge us based on what /we/ did. You cannot tell God that
the reason why you willfully sinned is that you saw other people doing it.

Don't let the pressure from those around you dictate your life. In general, but
especially in your faith.

God made you so you could live the life He gave you. Allowing others to
guide your life in a direction you know God does not want you to go down is
dishonoring Christ in one of the most extreme ways. God created you to be who He
created you to be, don't let others lead you astray.

If you know something is not Sabbath-appropriate, whether it's with your friends
or with people you go to church with, do not participate. Tell your friends "I
can't do this on Saturday" or church folk "I don't believe this is right to do
on Sabbath". And if they have a problem with you, fine, you are honoring God and
it brings joy to His heart to see that you love Him above your friends, family,
and even church members.

* Exceptions to the Sabbath

Now, some of you may have been wondering, aren't there any exceptions to this?
And I want to tell you no since then you'll be prone to say you're always the
exception to the Sabbath rule. But there are cases, few and far between, where
doing something not typically Sabbath-appropriate may be encouraged.

- If someone is at the point of death, please bring them to the
hospital or find somehow to get them some food if that's what they need.
- If you're about to pass out, please service yourself and get some help.
- If someone is in danger, don't hesitate to call the police for help.

This concept is outlined in Mark

[[bible:Mark 3:4]]
#+begin_quote
4 Then He said to them, “Is it lawful on the Sabbath to do good or to do evil,
to save life or to kill?” But they kept silent.
#+end_quote

The danger we often find ourselves in when keeping Sabbath is that we always try
to make our cases the exception. "I *have* to study". "I *have* to go to
work". No. The world does not have to control you, you can allow God to be first
in your life.

Don't make yourself promises saying, "I'll break Sabbath for these 2 years, and
then after I graduate I will be faithful to God". "When I get promoted or a new
job I will be faithful to God."

Although it is grim to say, you don't know when *your* end is coming, you should
not want to perish in a state of disobedience to God.

* My Basketball testimony

I want to close out with a story.

I'm sure none of you will be surprised to find out that I used to play
basketball.

I was on the high school varsity basketball team from my sophomore year to my
senior year.

I would wake up early in the morning to do pushups or be working out while
watching basketball. I'd come to school before 7 am to practice in the morning,
and often wouldn't get back home until 8 or 9 pm because of practice after
school.

I was on the grind, and all of it was worth it for me. I wanted to play
basketball in college. It was my dream to play D1 basketball at Duke university,
and I was willing to do anything to get there.

And part of that required me to stop going to church. I read my bible and I
understood God, but I wanted something more than God. It doesn't matter what
"it" exactly was, but I wanted something more than God. SOMETHING about playing
basketball in college appealed to me more than God.

Instead of going to church, I would be at basketball practice or a basketball
game. And this went on for years.

In high school, we were pretty good. In my junior year, we were ranked as one of
the top schools in our division for the entire state of Virginia.

It was supposed to be my year, entirely.

And then, at the start of my junior year. I hurt my knee. I was supposed to be
in the starting five, but was immediately taken out.

In my mind, what I expected from my team was sympathy, love, and reassurance. But my
team all but forgot me while I was recovering. I received no texts asking how I
was doing or how I was dealing with the pain. I would just sit on the sidelines
and they'd only acknowledge me before I left.

That started making me think and that's when I started realizing that I was missing
something in my life. No one around me seemed to value me outside of what I
could provide on the basketball court.

A few weeks after the injury I was fully recovered and worked my way back into
the starting lineup.

We did very well that year and ended up making it to the state finals.

This was the moment high school basketball players dreamed of, this was the
stage in which people found hundreds of college coaches looking at them, all
desiring to find someone to bring to their college basketball program. During
our run to the state finals my coach had told me of multiple colleges that
wanted to come to see me.

So we get on the court for the championship game, fight and push and bleed like
we usually did, and win. For the first time in our school's history, we won the
basketball state championship. For the first time in over 20 years, a school
from our city won the basketball championship. We go back to the locker room,
and the blood, sweat, and tears for the moment we had been working so hard for
finally arrived.

#+begin_center
*And we felt nothing.*
#+end_center

As crazy as it might sound, we felt nothing.

We sat around in the locker room saying "I'm still waiting for it to set
in". All we felt was tired.

Over the coming weeks all of us, even the coach, would repeat those words, "I'm
still waiting for it to set in". And it never did.

This was my breaking point. For the next two months, I spent time reflecting on my
life. I fell into a depression and eventually decided to try to find a
solution to this deep loss of purpose in my heart. And as is the case for many
people who are broken by the world, I decided to go to church.

And it was when I involved myself wholly, and devoted myself to God and the
things of the church that I found purpose. I found that God forgives and that God
is in the business of loving people. That His love is so strong that He gave
away his life so that I could live.

A God who could forgive even me who only came to Him when I wanted to win a
basketball game. And after that summer, I realized I needed to make a change in my
life.

So before the season started, I went to my coach and told Him that I would not
play basketball on Sabbath. From sunset Friday to sunset Saturday, I would not
practice or play in a basketball game. It took me weeks to build up that
courage, it wasn't until I heard a preacher I was listening to say "Some of us
find a baseball game more important than God" that I gained the courage to have
that conversation.

This was my senior year of high school, I was supposed to be the captain of the
team. And now I was saying I couldn't attend half of the games we were supposed
to be playing because they were on the Sabbath.

The amount of hate I received for this could have broken me if it weren't for
God sustaining me. I would have my friends stop me in the halls and ask me why
I wasn't at the game or why I was giving up on the team. I had one of the school
staff pull me aside and tell me that I was abandoning the team. I'd have my
professors ask me questions. Everyone seemed to have an opinion on the decision
I made to follow God.

Soon after I made another decision, that I wouldn't play basketball in
college. This decision was met with more adversity than my decision not to play
on Sabbath. My parents are immigrants. Neither of them as of then had attended a
4-year university, nor would be able to afford to send me to one.

I had everyone from family to friends to teachers tell me I was making a
mistake. My coach would always come to me and tell me about the schools that
contacted him and wanted to talk to me. My answer was always the same.

I made this second decision because I believed God was calling me to a greater
purpose, to ministry. He was calling me to witness to my friends in college, be
someone to give bible studies, and help people on their faith walks. I wanted to
do ministry and devote my time to growing in God and growing others in God.

And people would always nag me, didn't you want to go to Duke? Be a D1 athlete,
be something special.

Since I was no longer going to play basketball in college and decided to apply
for college the normal way. A man from church sat down with me and showed me how
to find and apply to colleges. I was starting to learn about what colleges were
3 months before applications were due. I took the SAT twice during my senior
year of high school, I did take it once before that summer and did relatively
poorly.

I spent every moment applying for college and scholarships. I wrote over 50
essays, applied to around 100 scholarships, and because of my family's financial
situation was allowed to apply to 20 colleges for free. I did all of this on top
of taking 4 AP classes, still being the captain of the basketball team, and
holding 3 positions in my church including being a Sabbath school teacher and
preparing a lesson nearly every week.

I say all of this to show you that it is possible. The year before my conversion
I spent my free time outside of basketball practice playing video games, roughly
8 hours a day. God was able to kill that addiction so I had more time for the
difficult year ahead.

God had changed my heart so that even though I was only getting 5 to 6 hours of
sleep a night and was working tirelessly every single day, I felt joy in my
heart. I was obeying Him, and when you choose to obey God you start to grow, and
it feels /good/.

Time passed, and eventually, I got into Duke University, the college where I
wanted to play basketball at. Another few weeks passed, and I was accepted into
a scholarship that would pay for my entire schooling.

* Follow God

Let me tell you, as I close. Choose to follow God. Don't wait. I used to tell
myself before I was convicted, "after I play basketball and spend these years
breaking Sabbath, I'd go back to God".

I would tell myself I would break God's law and if I made it to the NBA, after
retiring I would devote myself to God, give my money away, and bring honor to
God by being successful. And here's the thing

#+begin_center
*God is more interested in you being His child than you being successful*
#+end_center

Your sacrifice may not end in you getting what you originally wanted, you
may end up not being able to get into school or fulfilling your dream. But let
me assure you, *An eternity with God is more satisfying than a life without
Him*.

Some of us will have to be making a difficult decision *today*. We will have to
choose to reject friends, family, coworkers, and the hardest of all ourselves to
follow God.

You don't know when Christ is coming back, don't play that game. Choose to
follow Him /now/. He wants to give you more joy, more satisfaction, and more
Godly success (Godly, not worldly success) than you could ever plan for your life.

He loved you so much that He decided to come down to the cross, and be crucified
painfully for your sins. Because you chose and continue to choose to break the
Sabbath he died on the cross. Because of your sins, He came down to suffer pain
and torture.

Choose to follow God. People will leave you in life. Your job will lay you off,
your university doesn't care about you, and your friends may abandon you no
matter how close you feel to them. I saw it when my basketball team practically
threw me aside while I was hurt, I had no longer become convenient to them, I
had no use. But God finds you beautiful, You are His son or daughter, and He
asks you to follow Him.

You don't know when Christ will return, do you want Him to find you disobeying
Him when returns, so make the decision now to follow God, make it now.

Make the decision now to follow God.
