* Preparation :noexport:
The goal of this study would be to give someone new to Christianity a multiple
day overview on what the bible teaches. I have to think about whether this would
get into how do we know Christianity is true, but I think it will.

The largest things to talk about are:
- Jesus!

Yup. I think the focus would be: what does the bible say about the state of
humans, what does it say it will do about it, who accomplishes all of this, how
do we accept this, and what happens once we accept this.
** Topics:
*** What exactly is the bible?
Explain the difference between the old testament and new testament and give
timelines for when each of them were written.
*** What does the bible say about the state of humans
The bible starts off with the story of how humans were in the ideal, how they
lived life to the fullest, but then found themselves in sin. What we see soon
after is a devolution of humans, where the new order was self preservation,
selfishness. We can see the root of all the horrible things humans do on the
earth today being selfishness.

But, God makes a promise. He speaks of someone who will right the wrongs humans
have done.

A potential hitting point is that the bible says that even though there is
suffering and pain, God is not aloof from the world. God is ever present and
working with us to bring us back to the ideal he created us in.

The same thing goes for our lives. When we go through difficult times, God is
not far away from us, he wants to see us get better, and we see that most
clearly in Jesus Christ who we'll talk about in the next lesson

Bring up how sacrifice was instituted to show that when we sin (are selfish),
the result of that is death. A phrase used a lot is "the wages of sin is death"
**** Questions that may come up
*** Jesus Christ
- Talk about the scene we painted in the previous lesson.
- God Himself decides to come down to earth. The incarnation
- He speaks and teaches people about the best way to live their lives
- He interestingly goes to the lower class people in society (humility)
- He's crucified
- He's resurrected
**** Questions that may come up
- Why not do Jesus' sacrifice immediately after sin?
  Maybe the God wanted us to see what sin manifested into so we knew how
  horrible it was. No matter what, God's timing is perfect
*** What happened after?
*** How can we believe it?
- Manuscriptural evidence!
